apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-uat
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Nomad-1111/n8n.git
    targetRevision: uat
    path: helm
    helm:
      valueFiles:
        - values-uat.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-uat

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
