# ============================================================================
# Argo CD Application - Production Environment
# ============================================================================
# This file defines an Argo CD Application resource that manages the
# deployment of n8n to the production environment. Argo CD monitors the
# Git repository and automatically syncs changes when detected.
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Application name - used to identify this application in Argo CD
  name: n8n-prod
  # Namespace where Argo CD is installed (typically 'argocd')
  namespace: argocd
spec:
  # Argo CD project - groups applications for access control
  project: default

  # Source configuration - defines where to get the application manifests
  source:
    # Git repository URL containing the Helm chart
    repoURL: https://github.com/Nomad-1111/n8n.git
    # Git branch or tag to monitor for changes
    # 'main' branch triggers deployments to production environment
    targetRevision: main
    # Path within repository containing Helm chart
    path: helm
    # Helm-specific configuration
    helm:
      # Values files to use when rendering the Helm chart
      # These files override default chart values
      valueFiles:
        - values-prod.yaml

  # Destination configuration - defines where to deploy the application
  destination:
    # Kubernetes cluster API server URL
    server: https://kubernetes.default.svc
    # Target namespace for deployment
    namespace: n8n-prod

  # Sync policy - defines how Argo CD manages application synchronization
  syncPolicy:
    # Automated sync configuration
    automated:
      # Prune: Automatically delete resources that are no longer in Git
      prune: true
      # Self-heal: Automatically correct drift from Git state
      selfHeal: true
    # Sync options - additional synchronization behaviors
    syncOptions:
      # CreateNamespace: Automatically create the target namespace if missing
      - CreateNamespace=true
