# ============================================================================
# Setup HTTPS with cert-manager for n8n
# ============================================================================
# This script installs cert-manager and creates a self-signed certificate
# issuer for local development. This enables HTTPS access to n8n instances.
# ============================================================================

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Setting up HTTPS with cert-manager" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# Step 1: Install cert-manager CRDs
Write-Host "Step 1: Installing cert-manager CRDs..." -ForegroundColor Yellow
$certManagerVersion = "v1.13.3"
kubectl apply -f "https://github.com/cert-manager/cert-manager/releases/download/$certManagerVersion/cert-manager.yaml" 2>&1 | Out-Null

if ($LASTEXITCODE -ne 0) {
    Write-Host "`n❌ Failed to install cert-manager CRDs" -ForegroundColor Red
    exit 1
}

Write-Host "✅ cert-manager CRDs installed" -ForegroundColor Green

# Step 2: Wait for cert-manager to be ready
Write-Host "`nStep 2: Waiting for cert-manager to be ready..." -ForegroundColor Yellow
Write-Host "This may take 1-2 minutes..." -ForegroundColor Gray

$maxAttempts = 30
$attempt = 0
$ready = $false

while ($attempt -lt $maxAttempts -and -not $ready) {
    $pods = kubectl get pods -n cert-manager --no-headers 2>&1
    if ($LASTEXITCODE -eq 0) {
        $runningPods = ($pods | Select-String "Running" | Measure-Object).Count
        $totalPods = ($pods | Measure-Object -Line).Count
        if ($runningPods -eq $totalPods -and $totalPods -gt 0) {
            $ready = $true
        }
    }
    if (-not $ready) {
        Start-Sleep -Seconds 2
        $attempt++
        Write-Host "." -NoNewline -ForegroundColor Gray
    }
}

if (-not $ready) {
    Write-Host "`n⚠️  cert-manager pods may still be starting. Continuing anyway..." -ForegroundColor Yellow
} else {
    Write-Host "`n✅ cert-manager is ready" -ForegroundColor Green
}

# Step 3: Create self-signed ClusterIssuer
Write-Host "`nStep 3: Creating self-signed certificate issuer..." -ForegroundColor Yellow

$issuerYaml = @"
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
"@

$issuerYaml | kubectl apply -f - 2>&1 | Out-Null

if ($LASTEXITCODE -eq 0) {
    Write-Host "✅ Self-signed ClusterIssuer created" -ForegroundColor Green
} else {
    Write-Host "⚠️  ClusterIssuer may already exist (this is okay)" -ForegroundColor Yellow
}

# Step 4: Verify installation
Write-Host "`nStep 4: Verifying installation..." -ForegroundColor Yellow

kubectl get pods -n cert-manager --no-headers 2>&1 | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-Host "`nCert-manager pods:" -ForegroundColor Cyan
    kubectl get pods -n cert-manager
}

kubectl get clusterissuer selfsigned-issuer 2>&1 | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-Host "`n✅ ClusterIssuer 'selfsigned-issuer' is ready" -ForegroundColor Green
} else {
    Write-Host "`n⚠️  ClusterIssuer not found. It may still be creating..." -ForegroundColor Yellow
}

Write-Host "`n========================================" -ForegroundColor Green
Write-Host "✅ HTTPS Setup Complete!" -ForegroundColor Green
Write-Host "========================================`n" -ForegroundColor Green

Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Update your Helm values files to use HTTPS:" -ForegroundColor White
Write-Host "   - Set ingress.protocol: https" -ForegroundColor Gray
Write-Host "   - Configure ingress.tls section" -ForegroundColor Gray
Write-Host "   - Set secureCookie: true" -ForegroundColor Gray
Write-Host "`n2. Argo CD will automatically sync the changes" -ForegroundColor White
Write-Host "`n3. Certificates will be automatically generated by cert-manager" -ForegroundColor White
Write-Host "`n4. Access n8n via HTTPS (you'll need to accept the self-signed certificate)" -ForegroundColor White
Write-Host "   - Dev:  https://n8n-dev.local" -ForegroundColor Gray
Write-Host "   - UAT:  https://n8n-uat.local" -ForegroundColor Gray
Write-Host "   - Prod: https://n8n-prod.local" -ForegroundColor Gray

# Optional: Set up Let's Encrypt for production
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Optional: Let's Encrypt Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "`nFor production with real domains, you can use Let's Encrypt instead of self-signed." -ForegroundColor Yellow
Write-Host "This provides trusted certificates (no browser warnings)." -ForegroundColor Yellow
Write-Host "`nRequirements:" -ForegroundColor White
Write-Host "  - Real domain name (e.g., n8n.yourdomain.com)" -ForegroundColor Gray
Write-Host "  - DNS pointing to your cluster's ingress controller" -ForegroundColor Gray
Write-Host "  - Public accessibility (Let's Encrypt must reach your cluster)" -ForegroundColor Gray
Write-Host "`nSee docs/LETSENCRYPT_SETUP.md for detailed instructions." -ForegroundColor Cyan

$setupLetsEncrypt = Read-Host "`nDo you want to set up Let's Encrypt issuer now? (y/N)"
if ($setupLetsEncrypt -eq "y" -or $setupLetsEncrypt -eq "Y") {
    Write-Host "`nSetting up Let's Encrypt..." -ForegroundColor Yellow
    $scriptPath = Join-Path $PSScriptRoot "setup-letsencrypt.ps1"
    if (Test-Path $scriptPath) {
        & $scriptPath
    } else {
        Write-Host "⚠️  setup-letsencrypt.ps1 not found. Please run it manually." -ForegroundColor Yellow
        Write-Host "   Command: .\scripts\setup-letsencrypt.ps1" -ForegroundColor Gray
    }
} else {
    Write-Host "`nSkipping Let's Encrypt setup." -ForegroundColor Gray
    Write-Host "You can set it up later by running: .\scripts\setup-letsencrypt.ps1" -ForegroundColor Gray
}

